### ISSUE TITLE
Simultaneous upload of >4 files results in errors

### ISSUE THREAD

**Issue by Jrhotrod** [espebra/filebin#24] opened 2020-04-11 03:12 UTC
Attempting to simultaneously upload more than four files into a bin results in an error: `Filebin is currently unavailable. Please retry later.` However, the upload of the same files one at a time, or in smaller quantities than four at once, works just fine. 
This four-file limitation has also been observed by my friends that use this platform for file transfers. 
I'm more than happy to provide further details if needed!

**Comment by espebra** [comment] 2020-04-15 06:59
Hi,

Thank you for the report. I need some help to reproduce this. How big (roughly) are the files? Is it sufficient with 5-10 files to reproduce?

**Comment by Jrhotrod** [comment] 2020-04-18 04:00
Hey, thanks for the reply!

The files are about an average of 120 MB each. 5-10 files will do just fine.

Also, I'm uploading *.flac files. However, I can test it more with other file types to help you if you like.

**Comment by espebra** [comment] 2020-04-18 20:25
I was asking for images specifically because they are processed (thumbnails are created), but all other files are just written and checksummed. Does the errors appear next to the progress bars during upload or is entire filebin unavailable? From the error message in your initial report it seems like it is the latter, which is a bit weird.

**Comment by Jrhotrod** [comment] 2020-04-20 08:27
The errors appear on the progress bar, which turns red and says that Filebin isn't available. I can make some time to replicate the issue in the coming days, and send you a screenshot, along with the files that I attempted to upload.

**Comment by espebra** [comment] 2020-09-26 21:03
This is still weird, but I'll not look into fixing it. Instead I'm putting that time into getting filebin version 2 ready and released. It is currently available on https://dev.filebin.net/.

I know it's a while since you've reported this issue, but if you still find that this is a real problem for you, can you please give the development environment a spin and see if the issue occurs there? This is running filebin2 and I believe this problem does not occur there.

**Comment by Jrhotrod** [comment] 2020-09-27 17:58
I will have another look at it! I have not been using Filebin very much until the past few days, so I will try to bring back the issue on the main Filebin and the dev environment. Thanks for your work!

**Comment by espebra** [comment] 2020-12-24 22:34
I'm closing this now. I'm pretty sure this is not a problem in https://github.com/espebra/filebin2.

**Closed by espebra** 2020-12-24 22:34 UTC
